### ISSUE TITLE
Extended API for quickly drawing images

### ISSUE THREAD

**Issue by Zorbn** [lyte2d/lyte2d#45]
Currently drawing images requires using matrices for transformations like rotation, scaling, etc. This is probably the most robust way to draw things in Lyte, but there is still room for some extra versions of common functions to allow quickly drawing an image with rotation/scale on the fly.

One way to do this would be to have a simple version of each function as well as a complex one that takes additional parameters, then the user can pick based on the situation.

For example:
```lua
function draw_image(image: Image, dest_x: number, dest_y: number): void
function draw_image(image: Image, dest_x: number, dest_y: number, scale_x: number, scale_y: number, origin_x: number, origin_y: number, angle: number): void

function draw_image_rect(image: Image, dest_x: number, dest_y: number, src_x: number, src_y: number, rect_width: number, rect_height: number): void
function draw_image_rect(image: Image, dest_x: number, dest_y: number, src_x: number, src_y: number, rect_width: number, rect_height: number, scale_x: number, scale_y: number, origin_x: number, origin_y: number, angle: number): void


function add_imagebatch_rect(imagebatch: ImageBatch, dest_x: number, dest_y: number, src_x: number, src_y: number, rect_width: number, rect_height: number): void
function add_imagebatch_rect(imagebatch: ImageBatch, dest_x: number, dest_y: number, dest_width: number, dest_height: number, src_x: number, src_y: number, src_width: number, src_height: number, scale_x: number, scale_y: number, origin_x: number, origin_y: number, angle: number): void
```
(I'm not sure if sokol_gp will allow us to implement an angle parameter for `add_imagebatch_rect`)

**Comment by morew4rd** [comment]
Thanks for filing this!

Re extended version of `add_imagebatch_rect`. 

I think it's either rotation or batching, but need to take a closer look at both sokol and sokol_gp to see if this assumption is true :)

Also, we won't need `scale_x` and `scale_y` as they're implicit in `dest_width / src_width` and `dest_height / src_height`.

**Comment by morew4rd** [comment]
Also, do you think we should have a set of arguments for the origin point for scale? Or should it be the same point as rotate?

**Comment by Zorbn** [comment]
I think the same origin for both scale and rotate it fine, with the matrix api being there for more advanced things.
